function! GetVisualSelection()
    let [line_start, col_start] = getpos("'<")[1:2]
    let [line_end, col_end] = getpos("'>")[1:2]
    let lines = getline(line_start, line_end)
    let lines[-1] = lines[-1][:col_end-1]
    let lines[0] = lines[0][col_start-1:]
    return join(lines, "\n")
endfunction

let &t_ut=''
set nocompatible
set nowrap
set ignorecase
set tabstop=4
set shiftwidth=4
set expandtab
set autoindent
set number
set termguicolors
syntax on
filetype plugin indent on
colorscheme habamaxnew

command! -range Cclip :call system('echo ' . shellescape(GetVisualSelection()) . ' | xclip -selection clipboard')

vnoremap <space>_ :Cclip<CR>
map <space>tn :tabnext<CR>
map <space>tp :tabprevious<CR>
map <space>tt :tabnew<CR>
map <space>w :w<CR>
